openapi: 3.0.1
info:
  contact:
    email: hello@mainnet.cash
  description: "A high-level developer friendly bitcoin cash wallet api\nThis API\
    \ is currently in active development, breaking changes may \nbe made prior to\
    \ official release of version 1.\n\n**Important:** modifying this library to prematurely\
    \ operate on mainnet\nmay result in loss of funds\n"
  license:
    name: MIT Licence
    url: https://github.com/mainnet-cash/mainnet-js/blob/master/LICENSE
  termsOfService: https://mainnet.cash/terms/
  title: Mainnet Cash
  version: 0.0.3
externalDocs:
  description: Find out more about mainnet-js
  url: https://mainnet.cash
servers:
- url: http://localhost:3000/v1
tags:
- description: Interact with wallets
  externalDocs:
    description: Find out more
    url: /api-doc/#/wallet/
  name: wallet
- description: Interact with contracts
  externalDocs:
    description: Find out more
    url: /api-doc/#/contract/
  name: contract
paths:
  /contract/escrow/create:
    post:
      operationId: createEscrow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EscrowRequest'
        description: Request a new escrow contract
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EscrowResponse'
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: Create an escrow contract
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /contract/escrow/utxos:
    post:
      description: "Returns all UTXOs that can be spent by the \ncontract. Both confirmed\
        \ and unconfirmed UTXOs are included.\n"
      operationId: escrowUtxos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contract'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtxoResponse'
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: List specific utxos in a contract
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /contract/escrow/finalize:
    post:
      operationId: escrowFinalize
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EscrowFinalizeRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EscrowResponse'
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: Finalize an escrow contract
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /wallet/create:
    post:
      operationId: createWallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletRequest'
        description: Request a new random wallet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletResponse'
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: Create a new wallet
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/balance:
    post:
      operationId: balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request for a wallet balance
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
          description: successful operation
      summary: Get total balance for wallet
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/deposit_address:
    post:
      operationId: depositAddress
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request for a deposit address given a wallet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepositAddressResponse'
          description: successful operation
      summary: Get a deposit address in cash address format
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/deposit_qr:
    post:
      operationId: depositQr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request for a deposit cash address as a Quick Response code (qrcode)
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScalableVectorGraphic'
          description: "A Qr code image data encoded string in the src field suitable\
            \ for inclusion in html using:\n    - \\<img src\\=\\\"{response.src}\"\
            \\>                \n"
      summary: Get receiving cash address as a qrcode
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/max_amount_to_send:
    post:
      operationId: maxAmountToSend
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaxAmountToSendRequest'
        description: get amount that will be spend with a spend max request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
        "418":
          content: {}
          description: Invalid network for given address
      summary: Get maximum spendable amount
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/send:
    post:
      operationId: send
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRequest'
        description: place a send request
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
        "418":
          content: {}
          description: Invalid network for given address
      summary: Send some amount to a given address
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/send_max:
    post:
      operationId: sendMax
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMaxRequest'
        description: Request to all available funds to a given address
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMaxResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
      summary: Send all available funds to a given address
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/utxos:
    post:
      operationId: utxos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request detailed list of unspent transaction outputs
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtxoResponse'
          description: successful operation
      summary: Get detailed information about unspent outputs (utxos)
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
components:
  schemas:
    EscrowRequest:
      example:
        arbiterAddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        buyerAddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        sellerAddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
      properties:
        buyerAddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          format: ((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}
          type: string
        arbiterAddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          format: ((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}
          type: string
        sellerAddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          format: ((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}
          type: string
      required:
      - walletId
    CashaddrFormat:
      example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
      format: ((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}
      type: string
    EscrowResponse:
      allOf:
      - $ref: '#/components/schemas/Contract'
      required:
      - contractId
    Contract:
      example:
        contractId: contractId
      properties:
        contractId:
          description: |
            serialized contract
          type: string
      required:
      - contractId
    UtxoResponse:
      example:
        utxos:
        - amount:
            unit: sat
            value: 100
          index: 0.8008281904610115
        - amount:
            unit: sat
            value: 100
          index: 0.8008281904610115
      properties:
        utxos:
          items:
            $ref: '#/components/schemas/Utxo'
          type: array
    Utxo:
      allOf:
      - $ref: '#/components/schemas/Outpoint'
      - $ref: '#/components/schemas/TransactionId'
      example:
        amount:
          unit: sat
          value: 100
        index: 0.8008281904610115
      properties:
        index:
          type: number
        amount:
          $ref: '#/components/schemas/Amount'
      required:
      - amount
      - transaction
      - utxoId
    Outpoint:
      properties:
        utxoId:
          description: serialized outpoint
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
          type: string
    TransactionId:
      properties:
        transactionId:
          description: The hash of a transaction in hex format
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
    Amount:
      example:
        unit: sat
        value: 100
      properties:
        value:
          example: 100
          type: number
        unit:
          description: Denomination for amount
          enum:
          - bch
          - usd
          - bit
          - bits
          - sat
          - sats
          - satoshi
          - satoshis
          example: sat
          type: string
    EscrowFinalizeRequest:
      allOf:
      - $ref: '#/components/schemas/SerializedWallet'
      - $ref: '#/components/schemas/Contract'
      example:
        action: complete
        utxoIds:
        - 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
        - 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
      properties:
        action:
          $ref: '#/components/schemas/EscrowAction'
        utxoIds:
          items:
            $ref: '#/components/schemas/OutputItem'
          type: array
    SerializedWallet:
      example:
        walletId: testnet:wif:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
      properties:
        walletId:
          description: |
            Serialized wallet returned in `walletId` field of /wallet/create call
          example: testnet:wif:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          format: password
          type: string
      required:
      - walletId
    EscrowAction:
      description: Action for finalization of contract.
      enum:
      - complete
      - refund
      example: complete
      type: string
    UtxoIds:
      items:
        $ref: '#/components/schemas/OutputItem'
      type: array
    OutputItem:
      description: serialized outpoint
      example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
      type: string
    WalletRequest:
      allOf:
      - $ref: '#/components/schemas/WalletType'
      - $ref: '#/components/schemas/Network'
      example:
        type: wif
        network: testnet
        name: username1
      properties:
        name:
          description: User defined string for wallet
          example: username1
          type: string
      required:
      - name
      - network
      - type
      type: object
    WalletType:
      properties:
        type:
          description: Wallet type, either a single wallet with private key (wif)
            or a Hierarchical Deterministic wallet determined from a seed.
          enum:
          - wif
          - hd
          example: wif
          type: string
    Network:
      properties:
        network:
          description: network type
          enum:
          - mainnet
          - testnet
          - regtest
          - simtest
          example: testnet
          type: string
    WalletResponse:
      allOf:
      - $ref: '#/components/schemas/SerializedWallet'
      - $ref: '#/components/schemas/Network'
      example:
        cashaddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        wif: cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        name: username1
      properties:
        wif:
          description: |
            The wallet in Wallet Import Format (WIF)
          example: cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        name:
          description: User defined string for wallet
          example: username1
          type: string
        cashaddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          format: ((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}
          type: string
      type: object
    BalanceResponse:
      example:
        bch: 1
        sat: 100000000
        usd: 438.02
      properties:
        bch:
          description: Amount in whole Bitcoin Cash
          example: 1
          format: float
          type: number
        sat:
          description: Amount in satoshis
          example: 100000000
          type: integer
        usd:
          description: Amount in United States Dollars
          example: 438.02
          type: number
    DepositAddressResponse:
      allOf:
      - $ref: '#/components/schemas/Cashaddr'
    Cashaddr:
      properties:
        cashaddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          format: ((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}
          type: string
    ScalableVectorGraphic:
      example:
        src: data:image/svg+xml;base64,PD94bWwgdm... ==**
      properties:
        src:
          description: "A Qr code image data in svg format as utf-8 encoded string.\n\
            Suitable for inclusion in html using:\n    - \\<img src\\=\\\"**data:image/svg+xml;base64,PD94bWwgdm...\
            \ ==**\"\\>                \n"
          example: data:image/svg+xml;base64,PD94bWwgdm... ==**
          type: string
    MaxAmountToSendRequest:
      allOf:
      - $ref: '#/components/schemas/SerializedWallet'
      example:
        outputCount: 0
      properties:
        outputCount:
          description: |
            (optional) if sending all funds to multiple addresses, the
            count of the number of address funds will be sent
            to may be included.
          format: int32
          type: integer
      required:
      - walletId
    SendRequest:
      allOf:
      - $ref: '#/components/schemas/SerializedWallet'
      example:
        to:
        - amount:
            unit: sat
            value: 100
        - amount:
            unit: sat
            value: 100
      properties:
        to:
          items:
            $ref: '#/components/schemas/SendRequestItem'
          type: array
      required:
      - walletId
      type: object
    SendRequestItem:
      allOf:
      - $ref: '#/components/schemas/ToCashaddr'
      example:
        amount:
          unit: sat
          value: 100
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
      required:
      - cashaddr
      type: object
    ToCashaddr:
      properties:
        cashaddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          format: ((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}
          type: string
    SendResponse:
      allOf:
      - $ref: '#/components/schemas/TransactionId'
      example:
        balance:
          bch: 1
          sat: 100000000
          usd: 438.02
      properties:
        balance:
          $ref: '#/components/schemas/BalanceResponse'
      type: object
    SendMaxRequest:
      allOf:
      - $ref: '#/components/schemas/SerializedWallet'
      - $ref: '#/components/schemas/ToCashaddr'
      example:
        utxoIds:
        - 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
        - 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
      properties:
        utxoIds:
          items:
            $ref: '#/components/schemas/OutputItem'
          type: array
      required:
      - cashaddr
      - walletId
    SendMaxResponse:
      allOf:
      - $ref: '#/components/schemas/TransactionId'
      example:
        balance:
          bch: 0
          sat: 0
          usd: 0
      properties:
        balance:
          $ref: '#/components/schemas/ZeroBalanceResponse'
      type: object
    ZeroBalanceResponse:
      example:
        bch: 0
        sat: 0
        usd: 0
      properties:
        bch:
          description: Amount in whole Bitcoin Cash
          example: 0
          format: float
          type: number
        sat:
          description: Amount in satoshis
          example: 0
          type: integer
        usd:
          description: Amount in United States Dollars
          example: 0
          type: number
